ppx:
  DS: ${mysql.smb_fee}

ali-yun:
  ons:
    producer:
      properties:
        GROUP_ID: GID-risk-control
        AccessKey: ${middleware.ons.access-key}
        SecretKey: ${middleware.ons.secret-key}
        NAMESRV_ADDR: ${middleware.ons.smb.nameserver}
    consumer:
      properties:
        GROUP_ID: GID-risk-control
        AccessKey: ${middleware.ons.access-key}
        SecretKey: ${middleware.ons.secret-key}
        NAMESRV_ADDR: ${middleware.ons.smb.nameserver}

# dubbo配置
dubbo:
  application:
    name: smb-fee
    owner: wangc
  config-center:
    address: zookeeper://${middleware.zk.address}
    group: coordination
  protocol:
    port: 20881
  consumer:
    check: false
  provider:
    #    去除默认异常,使用B2B生成的异常过滤器
    filter: -exception
  logByCode: true

job:
  executor:
    app-name: ${ppx.name}
    logRetentionDays: ${job.fm.executor.log-retention-days}
  accessToken: ${job.fm.access-token}
  admin:
    addresses: ${job.fm.admin.addresses}